"""empty message

Revision ID: bc973d723d20
Revises: 1fb7794608a5
Create Date: 2024-04-18 01:47:05.557545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc973d723d20'
down_revision = '1fb7794608a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('personajes_favoritos')
    op.drop_table('planetas_favoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas_favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], name='planetas_favoritos_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='planetas_favoritos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planetas_favoritos_pkey')
    )
    op.create_table('personajes_favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], name='personajes_favoritos_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='personajes_favoritos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personajes_favoritos_pkey')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###
